// <auto-generated />
using ManagerCVAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagerCVAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230712131819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManagerCVAPI.Model.Sede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Città")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecapitoTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sedi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cap = "80143",
                            Città = "Napoli",
                            Email = "info.napoli@bcsoft.net",
                            Indirizzo = "Via Taddeo da Sessa - Centro direzionale isola F10",
                            Provincia = "Napoli",
                            RecapitoTel = "0815536002"
                        },
                        new
                        {
                            Id = 2,
                            Cap = "00144",
                            Città = "Roma",
                            Email = "info.roma@bcsoft.net",
                            Indirizzo = "Viale della Tecnica, 245",
                            Provincia = "Roma",
                            RecapitoTel = "068080237"
                        },
                        new
                        {
                            Id = 3,
                            Cap = "50123",
                            Città = "Firenze",
                            Email = "info.firenze@bcsoft.net",
                            Indirizzo = "Via Borgo Ognissanti 54",
                            Provincia = "Firenze",
                            RecapitoTel = "0559861922"
                        },
                        new
                        {
                            Id = 4,
                            Cap = "40121",
                            Città = "Bologna",
                            Email = "info.bologna@bcsoft.net",
                            Indirizzo = "Via Majani 2",
                            Provincia = "Bologna",
                            RecapitoTel = "0519921991"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
